spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/book-store"
    username: "postgres"
    password: "superuser"
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    #    generate-ddl: false
    #    open-in-view: false
    hibernate:
      ddl-auto: update